version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"  # Host port 8000 mapped to container port 8000
    networks:
      - stock_prediction_net

  streamlit:
    image: python:3.11
    container_name: streamlit_container
    volumes:
      - ./streamlit:/streamlit
    working_dir: /streamlit
    command: ["streamlit", "run", "app.py"]
    ports:
      - "8501:8501"  # Host port 8501 mapped to container port 8501
    depends_on:
      - fastapi
    networks:
      - stock_prediction_net

networks:
  stock_prediction_net:
    driver: bridge
